baseURL = "https://guenbenn.github.io"
languageCode = "vi-vn"
title = "nguyenben is a dev"
theme = "hugo-coder"

[params]
  author = "Nguyễn Công Ben"
  info = "Full Stack DevOps"
  gravatar = "nben940665@gmail.com"
  since = 2025
  colorScheme = "auto"

# Social links
[[params.social]]
  name = "GitHub"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/guenbenn"
  target = "_blank"
[[params.social]]
  name = "Telegram"
  icon = "fa-brands fa-telegram fa-2x"
  weight = 2
  url = "https://t.me/guen_benn"
  target = "_blank"
[[params.social]]
  name = "Facebook"
  icon = "fa-brands fa-facebook fa-2x"
  weight = 3
  url = "https://www.facebook.com/nguyen.ben.298372"
  target = "_blank"
[[params.social]]
  name = "Discord"
  icon = "fa-brands fa-discord fa-2x"
  weight = 4
  url = "https://discord.com/users/ben6506"
  target = "_blank"

# Menu links
[[menu.main]]
  name = "Bài Viết"
  weight = 1
  url = "posts"
[[menu.main]]
  name = "Dự Án"
  weight = 2
  url = "projects"
[[menu.main]]
  name = "Liên Hệ"
  weight = 3
  url = "contact"