const language = new URL(location.href).searchParams.get('lang') === 'en' ? 'en' : 'vi';
const response = await fetch('./copy.json');
if (!response.ok) throw new Error('Banner translations could not be loaded.');
const copy = (await response.json())[language];
document.documentElement.lang = language;
document.title = `Polaris 1.0.0 — ${language.toUpperCase()} social banner`;
document.querySelector('.banner').setAttribute('aria-label', copy.label);
document.querySelector('.byline').textContent = copy.byline;
const heading = document.querySelector('h1');
heading.replaceChildren(document.createTextNode(copy.headline[0]), document.createElement('br'));
const secondLine = document.createElement('span'); secondLine.textContent = copy.headline[1]; heading.append(secondLine);
document.querySelector('.copy p').replaceChildren(document.createTextNode(copy.intro[0]), document.createElement('br'), document.createTextNode(copy.intro[1]));
document.querySelectorAll('.features span').forEach((item, index) => { item.textContent = copy.features[index]; });
document.querySelector('.diagram').setAttribute('aria-label', copy.diagram);
document.querySelector('.diagram-caption > span:last-child').textContent = copy.caption;
document.querySelector('.tool > span:last-child').textContent = copy.tools;
document.querySelector('.diagram-footer').lastChild.textContent = copy.note;
document.querySelector('.facts > span:first-child').lastChild.textContent = ` ${copy.providers}`;
document.querySelector('.facts > span:last-child').lastChild.textContent = ` ${copy.languages}`;
